
SCENE_NAME = "Scene"
FRAME_OBJECT_NAME = "Frame"
PICTURE_OBJECT_NAME = "Picture"
ARTWORK_LABEL_OBJECT_NAME = "Artwork Label"
PICTURE_MATERIAL_NAME = "Picture Material"
PICTURE_MATERIAL_TEXTURE_NAME = "Image Texture"

TOP_FRAME_EDGE_VERTEX_GROUP = "Top Frame Edge"
TOP_PICTURE_EDGE_VERTEX_GROUP = "Top Picture Edge"

EXPORTABLE_OBJECTS = [FRAME_OBJECT_NAME, PICTURE_OBJECT_NAME]
